Repository sendOwlOrganization/SendOwl, pull requests merged in 2022-11, with the labels that each got.

#99 Fix/alarm&user entity
  src/main/java/com/example/sendowl/api/controller/AlarmController.java
  src/main/java/com/example/sendowl/api/service/AlarmService.java
  src/main/java/com/example/sendowl/domain/alarm/dto/AlarmChkDto.java
  src/main/java/com/example/sendowl/domain/alarm/entity/AlarmChk.java
  src/main/java/com/example/sendowl/domain/alarm/exception/AlarmNotFoundException.java
  src/main/java/com/example/sendowl/domain/alarm/exception/AlarmTypeExistException.java
  src/main/java/com/example/sendowl/domain/alarm/exception/AlarmTypeNotFoundException.java
  src/main/java/com/example/sendowl/domain/alarm/exception/enums/AlarmErrorCode.java
  src/main/java/com/example/sendowl/domain/alarm/exception/handler/AlarmExceptionHandler.java
  src/main/java/com/example/sendowl/domain/user/entity/User.java
Labels: fix

#104 Fix/user 랜덤으로 엠비티아이 닉네임을 생성해준다.
  src/main/java/com/example/sendowl/api/controller/UserController.java
  src/main/java/com/example/sendowl/api/service/UserService.java
  src/main/java/com/example/sendowl/domain/user/dto/UserDto.java
  src/main/resources/mbti-feature.txt
  src/test/java/com/example/sendowl/user/UserControllerTest.java
  src/test/java/com/example/sendowl/user/UserServiceTest.java
Labels: enhancement, fix

#105 fix/file
  src/main/java/com/example/sendowl/api/controller/FileController.java
  src/main/java/com/example/sendowl/api/file/FileApi.java
  src/main/java/com/example/sendowl/api/service/FileService.java
  src/main/resources/.application.yml.swp
  upload/2022/11/06/0cfd91dc-bdbd-42e3-9fed-10b70cff8903_logo.png
  upload/2022/11/06/76e3472c-9728-467d-aaa4-376fa0f503bf_MonaLisa.jpeg
  upload/2022/11/06/a6ea9d40-bd79-4c05-92dd-2e0ba03cd8b3_MonaLisa.jpeg
  upload/2022/11/06/b84d0e9f-a372-466d-b08d-702467633357_MonaLisa.jpeg
Labels: fix

#106 Fix/comment
  src/main/java/com/example/sendowl/domain/comment/dto/CommentDto.java
  src/main/java/com/example/sendowl/domain/user/dto/UserDto.java
Labels: enhancement, fix

#108 Feat/like
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/example/sendowl/api/controller/LikeController.java
  src/main/java/com/example/sendowl/api/service/LikeService.java
  src/main/java/com/example/sendowl/common/entity/BaseEntity.java
  src/main/java/com/example/sendowl/domain/board/dto/BoardDto.java
  src/main/java/com/example/sendowl/domain/board/entity/Board.java
  src/main/java/com/example/sendowl/domain/board/entity/BoardLike.java
  src/main/java/com/example/sendowl/domain/board/exception/enums/BoardErrorCode.java
  src/main/java/com/example/sendowl/domain/board/repository/BoardRepository.java
  src/main/java/com/example/sendowl/domain/like/dto/LikeDto.java
  src/main/java/com/example/sendowl/domain/like/entity/BoardLike.java
  src/main/java/com/example/sendowl/domain/like/exception/LikeNoAuthException.java
  src/main/java/com/example/sendowl/domain/like/exception/LikeNotFoundException.java
  src/main/java/com/example/sendowl/domain/like/exception/enums/LikeErrorCode.java
  src/main/java/com/example/sendowl/domain/like/exception/handler/LikeExceptionHandler.java
  src/main/java/com/example/sendowl/domain/like/repository/BoardLikeRepository.java
  src/main/java/com/example/sendowl/domain/user/entity/User.java
  src/test/java/com/example/sendowl/like/BoardLikeServiceTest.java
Labels: enhancement

#109 Feat/like
  src/main/java/com/example/sendowl/SendOwlApplication.java
  src/main/java/com/example/sendowl/api/controller/LikeController.java
  src/main/java/com/example/sendowl/api/service/LikeService.java
  src/main/java/com/example/sendowl/domain/board/repository/BoardRepository.java
  src/main/java/com/example/sendowl/domain/comment/dto/CommentDto.java
  src/main/java/com/example/sendowl/domain/comment/entity/Comment.java
  src/main/java/com/example/sendowl/domain/comment/entity/CommentLike.java
  src/main/java/com/example/sendowl/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/sendowl/domain/like/dto/LikeDto.java
  src/main/java/com/example/sendowl/domain/like/entity/CommentLike.java
  src/main/java/com/example/sendowl/domain/like/repository/CommentLikeRepository.java
  src/main/java/com/example/sendowl/domain/user/entity/User.java
Labels: enhancement
