Repository sendOwlOrganization/SendOwl, pull requests merged in 2022-03, with the labels that each got.

#1 Feat/signup
  pom.xml
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/controller/MemberController.java
  src/main/java/com/example/sendowl/controller/SwaggerController.java
  src/main/java/com/example/sendowl/controller/UserController.java
  src/main/java/com/example/sendowl/dto/MemberResponse.java
  src/main/java/com/example/sendowl/entity/Member.java
  src/main/java/com/example/sendowl/excption/MemberNotFoundException.java
  src/main/java/com/example/sendowl/repository/MemberRepository.java
  src/main/java/com/example/sendowl/service/CustomUserDetailService.java
  src/main/java/com/example/sendowl/service/MemberService.java
  src/main/java/com/example/sendowl/util/JwtAuthenticationFilter.java
  src/main/java/com/example/sendowl/util/JwtProvider.java
  src/main/resources/application-jwt.yml
  src/main/resources/application.yml
Labels: enhancement

#2 feat: MemberNotValidException
  src/main/java/com/example/sendowl/excption/MemberNotValidException.java
  src/main/java/com/example/sendowl/service/MemberService.java
Labels: enhancement

#3 Board 관련 + findAll() error
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/controller/BoardController.java
  src/main/java/com/example/sendowl/dto/BoardRequest.java
  src/main/java/com/example/sendowl/dto/BoardResponse.java
  src/main/java/com/example/sendowl/entity/Board.java
  src/main/java/com/example/sendowl/repository/BoardRepository.java
  src/main/java/com/example/sendowl/service/BoardService.java
Labels: bug

#5 board Controller 에서 url naming 확인 부탁여
  src/main/java/com/example/sendowl/controller/BoardController.java
  src/main/java/com/example/sendowl/dto/BoardRequest.java
  src/main/java/com/example/sendowl/entity/Board.java
  src/main/java/com/example/sendowl/repository/BoardRepository.java
  src/main/java/com/example/sendowl/service/BoardService.java
Labels: help wanted

#6 feat: construct board detail api
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/controller/BoardController.java
  src/main/java/com/example/sendowl/dto/BoardRequest.java
  src/main/java/com/example/sendowl/entity/Board.java
  src/main/java/com/example/sendowl/repository/BoardRepository.java
  src/main/java/com/example/sendowl/service/BoardService.java
Labels: documentation

#7 Comment
  src/main/java/com/example/sendowl/SendOwlApplication.java
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/controller/CommentController.java
  src/main/java/com/example/sendowl/dto/CommentRequest.java
  src/main/java/com/example/sendowl/entity/Board.java
  src/main/java/com/example/sendowl/entity/Comment.java
  src/main/java/com/example/sendowl/repository/CommentRepository.java
  src/main/java/com/example/sendowl/service/CommentService.java
Labels: bug, enhancement

#9 NestedComment
  src/main/java/com/example/sendowl/controller/CommentController.java
  src/main/java/com/example/sendowl/entity/Board.java
  src/main/java/com/example/sendowl/entity/Member.java
  src/main/java/com/example/sendowl/repository/CommentRepository.java
  src/main/java/com/example/sendowl/service/CommentService.java
Labels: bug, enhancement

#10 fix: convert String to int (active Column) + ColumnDefault
  src/main/java/com/example/sendowl/controller/BoardController.java
  src/main/java/com/example/sendowl/entity/Board.java
  src/main/java/com/example/sendowl/entity/Cate.java
  src/main/java/com/example/sendowl/entity/Comment.java
  src/main/java/com/example/sendowl/entity/Member.java
  src/main/java/com/example/sendowl/repository/BoardRepository.java
  src/main/java/com/example/sendowl/service/BoardService.java
Labels: enhancement
