Repository sendOwlOrganization/SendOwl, pull requests merged in 2022-09, with the labels that each got.

#87 fix: editorJs error
  src/main/java/com/example/sendowl/api/controller/BoardController.java
  src/main/java/com/example/sendowl/common/converter/EditorJsHelper.java
  src/main/java/com/example/sendowl/domain/board/dto/BoardDto.java
Labels: fix

#89 fix: Summary Controller
  src/main/java/com/example/sendowl/api/controller/BoardController.java
  src/main/java/com/example/sendowl/api/controller/CategoryController.java
  src/main/java/com/example/sendowl/api/controller/CommentController.java
  src/main/java/com/example/sendowl/api/controller/FileController.java
  src/main/java/com/example/sendowl/api/controller/MbtiController.java
  src/main/java/com/example/sendowl/api/controller/SearchController.java
  src/main/java/com/example/sendowl/api/service/CategoryService.java
Labels: documentation

#90 Feat/oauth2
  src/main/java/com/example/sendowl/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/sendowl/auth/jwt/JwtProvider.java
  src/main/java/com/example/sendowl/config/SecurityConfig.java
Labels: fix

#91 Fix/board
  src/main/java/com/example/sendowl/api/controller/BoardController.java
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/common/converter/EditorJsHelper.java
  src/main/java/com/example/sendowl/config/SecurityConfig.java
  src/main/java/com/example/sendowl/domain/board/dto/BoardDto.java
Labels: fix

#93 Fix/auth
  src/main/java/com/example/sendowl/api/controller/BlameController.java
  src/main/java/com/example/sendowl/api/controller/BoardController.java
  src/main/java/com/example/sendowl/api/controller/CategoryController.java
  src/main/java/com/example/sendowl/api/controller/CommentController.java
  src/main/java/com/example/sendowl/api/controller/FileController.java
  src/main/java/com/example/sendowl/api/controller/UserController.java
  src/main/java/com/example/sendowl/auth/exception/enums/JwtErrorCode.java
  src/main/java/com/example/sendowl/auth/exception/handler/RestResponseEntityExceptionHandler.java
  src/main/java/com/example/sendowl/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/sendowl/auth/jwt/JwtProvider.java
  src/main/java/com/example/sendowl/config/SecurityConfig.java
Labels: enhancement, fix

#92 Add alarm
  src/main/java/com/example/sendowl/api/controller/AlarmController.java
  src/main/java/com/example/sendowl/api/service/AlarmService.java
  src/main/java/com/example/sendowl/api/service/BlameService.java
  src/main/java/com/example/sendowl/config/SecurityConfig.java
  src/main/java/com/example/sendowl/domain/alarm/dto/AlarmChkDto.java
  src/main/java/com/example/sendowl/domain/alarm/dto/AlarmDto.java
  src/main/java/com/example/sendowl/domain/alarm/entity/Alarm.java
  src/main/java/com/example/sendowl/domain/alarm/entity/AlarmChk.java
  src/main/java/com/example/sendowl/domain/alarm/entity/AlarmType.java
  src/main/java/com/example/sendowl/domain/alarm/repository/AlarmChkRepository.java
  src/main/java/com/example/sendowl/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/example/sendowl/domain/alarm/repository/AlarmTypeRepository.java
  src/main/java/com/example/sendowl/domain/blame/dto/BlameDto.java
  src/main/java/com/example/sendowl/domain/blame/dto/BlameType.java
  src/main/java/com/example/sendowl/domain/blame/entity/Blame.java
  src/main/java/com/example/sendowl/domain/blame/repository/BlameRepository.java
  src/main/java/com/example/sendowl/domain/blame/repository/BlameTypeRepository.java
Labels: new-feature

#94 Fix/swagger
  build.gradle
  src/main/java/com/example/sendowl/api/controller/AlarmController.java
  src/main/java/com/example/sendowl/api/controller/BlameController.java
  src/main/java/com/example/sendowl/api/controller/BoardController.java
  src/main/java/com/example/sendowl/api/controller/CategoryController.java
  src/main/java/com/example/sendowl/api/controller/CommentController.java
  src/main/java/com/example/sendowl/api/controller/FileController.java
  src/main/java/com/example/sendowl/api/controller/UserController.java
  src/main/java/com/example/sendowl/config/OpenApiConfig.java
Labels: documentation, enhancement

#95 Fix/board
  src/main/java/com/example/sendowl/api/controller/BoardController.java
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/domain/board/dto/BoardDto.java
Labels: enhancement, fix
