Repository sendOwlOrganization/SendOwl, pull requests merged in 2022-04, with the labels that each got.

#16 fix: change kafka port
  src/main/resources/application.yml
Labels: fix

#24 Fix(swagger) : fix configuration about swagger
  build.gradle
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: fix

#27 Refactor(domain): refactoring all entities
  .gitignore
  src/main/java/com/example/sendowl/auth/PrincipalDetails.java
  src/main/java/com/example/sendowl/auth/PrincipalDetailsService.java
  src/main/java/com/example/sendowl/config/JpaConfig.java
  src/main/java/com/example/sendowl/controller/BoardController.java
  src/main/java/com/example/sendowl/controller/CommentController.java
  src/main/java/com/example/sendowl/controller/MemberController.java
  src/main/java/com/example/sendowl/entity/BaseEntity.java
  src/main/java/com/example/sendowl/entity/Board.java
  src/main/java/com/example/sendowl/entity/Cate.java
  src/main/java/com/example/sendowl/entity/Category.java
  src/main/java/com/example/sendowl/entity/Comment.java
  src/main/java/com/example/sendowl/entity/Member.java
  src/main/java/com/example/sendowl/entity/board/Board.java
  src/main/java/com/example/sendowl/entity/board/BoardLike.java
  src/main/java/com/example/sendowl/entity/comment/Comment.java
  src/main/java/com/example/sendowl/entity/comment/CommentLike.java
  src/main/java/com/example/sendowl/entity/user/Role.java
  src/main/java/com/example/sendowl/entity/user/User.java
  src/main/java/com/example/sendowl/repository/BoardRepository.java
  src/main/java/com/example/sendowl/repository/CommentRepository.java
  src/main/java/com/example/sendowl/repository/MemberRepository.java
  src/main/java/com/example/sendowl/repository/UserRepository.java
  src/main/java/com/example/sendowl/service/BoardService.java
  src/main/java/com/example/sendowl/service/CommentService.java
  src/main/java/com/example/sendowl/service/CustomUserDetailService.java
  src/main/java/com/example/sendowl/service/MemberService.java
  src/main/resources/application.yml
Labels: refactoring

#28 Fix/jwt
  src/main/java/com/example/sendowl/auth/PrincipalDetailsService.java
  src/main/java/com/example/sendowl/controller/MemberController.java
  src/main/java/com/example/sendowl/entity/user/User.java
  src/main/java/com/example/sendowl/repository/UserRepository.java
  src/main/java/com/example/sendowl/service/CustomUserDetailService.java
  src/main/java/com/example/sendowl/service/MemberService.java
  src/main/java/com/example/sendowl/util/JwtProvider.java
Labels: fix

#29 Fix: board & add Converter
  src/main/java/com/example/sendowl/controller/BoardController.java
  src/main/java/com/example/sendowl/converter/BooleanToTFConverter.java
  src/main/java/com/example/sendowl/entity/BaseEntity.java
  src/main/java/com/example/sendowl/repository/BoardRepository.java
  src/main/java/com/example/sendowl/service/BoardService.java
Labels: fix

#32 Refactor(User): DTO, Controller, Service
  build.gradle
  src/main/java/com/example/sendowl/api/controller/MemberController.java
  src/main/java/com/example/sendowl/api/controller/SwaggerController.java
  src/main/java/com/example/sendowl/api/controller/UserController.java
  src/main/java/com/example/sendowl/api/service/MemberService.java
  src/main/java/com/example/sendowl/api/service/UserService.java
  src/main/java/com/example/sendowl/common/dto/BaseErrorResponse.java
  src/main/java/com/example/sendowl/common/dto/BaseErrorResponseDto.java
  src/main/java/com/example/sendowl/common/dto/BaseResponseDto.java
  src/main/java/com/example/sendowl/common/dto/ExceptionResponse.java
  src/main/java/com/example/sendowl/common/exception/enums/BaseErrorCode.java
  src/main/java/com/example/sendowl/common/exception/handler/BaseExceptionHandler.java
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/config/SwaggerConfig.java
  src/main/java/com/example/sendowl/domain/board/exception/handler/BoardExceptionHandler.java
  src/main/java/com/example/sendowl/domain/comment/exception/handler/CommentExceptionHandler.java
  src/main/java/com/example/sendowl/domain/user/dto/MemberRequest.java
  src/main/java/com/example/sendowl/domain/user/dto/MemberResponse.java
  src/main/java/com/example/sendowl/domain/user/dto/UserDto.java
  src/main/java/com/example/sendowl/domain/user/entity/User.java
  src/main/java/com/example/sendowl/domain/user/exception/enums/UserErrorCode.java
  src/main/java/com/example/sendowl/domain/user/exception/handler/UserExceptionHandler.java
  src/main/java/com/example/sendowl/domain/user/repository/UserRepository.java
  src/test/java/com/example/sendowl/user/UserControllerTest.java
Labels: refactoring

#33 Redis
  .gitignore
  build.gradle
  docker-compose.yml
  redis/redis.conf
  src/main/java/com/example/sendowl/api/controller/BoardController.java
  src/main/java/com/example/sendowl/api/controller/CommentController.java
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/api/service/CommentService.java
  src/main/java/com/example/sendowl/auth/jwt/RedisMessageSubscriber.java
  src/main/java/com/example/sendowl/auth/jwt/RedisShadowkey.java
  src/main/java/com/example/sendowl/config/RedisConfigure.java
  src/main/java/com/example/sendowl/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/sendowl/entity/RedisBoard.java
  src/main/java/com/example/sendowl/excption/RedisBoardNotFoundException.java
  src/main/java/com/example/sendowl/repository/RedisBoardRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/sendowl/redis/RedisRepositoryTest.java
Labels: enhancement, fix

#35 Fix .gitignore & redis file structure
  .gitignore
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/config/RedisConfigure.java
  src/main/java/com/example/sendowl/redis/RedisMessageSubscriber.java
  src/main/java/com/example/sendowl/redis/RedisShadowkey.java
  src/main/java/com/example/sendowl/redis/entity/RedisBoard.java
  src/main/java/com/example/sendowl/redis/excption/RedisBoardNotFoundException.java
  src/main/java/com/example/sendowl/repository/RedisBoardRepository.java
  src/test/java/com/example/sendowl/redis/RedisRepositoryTest.java
Labels: fix

#38 Feat: kafka로 인증 이메일 전송
  .gitignore
  build.gradle
  src/main/java/com/example/sendowl/api/controller/UserController.java
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/api/service/UserService.java
  src/main/java/com/example/sendowl/auth/jwt/JwtEnum.java
  src/main/java/com/example/sendowl/common/dto/BaseErrorResponseDto.java
  src/main/java/com/example/sendowl/config/RedisConfigure.java
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/domain/user/dto/UserDto.java
  src/main/java/com/example/sendowl/domain/user/exception/UserAlreadyExistException.java
  src/main/java/com/example/sendowl/domain/user/exception/UserVerifyTokenExpiredException.java
  src/main/java/com/example/sendowl/domain/user/exception/enums/UserErrorCode.java
  src/main/java/com/example/sendowl/domain/user/exception/handler/UserExceptionHandler.java
  src/main/java/com/example/sendowl/kafka/KafkaConsumerService.java
  src/main/java/com/example/sendowl/kafka/consumer/KafkaConsumer.java
  src/main/java/com/example/sendowl/kafka/dto/KafkaDto.java
  src/main/java/com/example/sendowl/kafka/enums/KafkaGroup.java
  src/main/java/com/example/sendowl/kafka/enums/KafkaTopic.java
  src/main/java/com/example/sendowl/kafka/producer/KafkaProducer.java
  src/main/java/com/example/sendowl/kafka/producer/KafkaProducerImpl.java
  src/main/java/com/example/sendowl/redis/RedisMessageSubscriber.java
  src/main/java/com/example/sendowl/redis/entity/RedisBoard.java
  src/main/java/com/example/sendowl/redis/entity/RedisEmailToken.java
  src/main/java/com/example/sendowl/redis/enums/RedisEnum.java
  src/main/java/com/example/sendowl/redis/exception/RedisBoardNotFoundException.java
  src/main/java/com/example/sendowl/redis/repository/RedisBoardRepository.java
  src/main/java/com/example/sendowl/redis/repository/RedisEmailTokenRepository.java
  src/main/java/com/example/sendowl/redis/service/RedisEmailTokenService.java
  src/main/java/com/example/sendowl/redis/service/RedisShadowKeyService.java
  src/main/java/com/example/sendowl/redis/sub/RedisMessageSubscriber.java
  src/main/java/com/example/sendowl/util/mail/MailDto.java
  src/main/java/com/example/sendowl/util/mail/MailService.java
  src/main/java/com/example/sendowl/util/mail/TokenGenerator.java
  src/main/resources/application.yml
  src/main/resources/templates/email-verification.html
  src/test/java/com/example/sendowl/redis/RedisRepositoryTest.java
  src/test/java/com/example/sendowl/redis/service/RedisEmailTokenServiceTest.java
Labels: refactoring, new-feature

#40 Jwt refectoring for ExceptionHandling
  src/main/java/com/example/sendowl/api/service/UserService.java
  src/main/java/com/example/sendowl/auth/exception/JwtInvalidException.java
  src/main/java/com/example/sendowl/auth/exception/JwtNotFoundException.java
  src/main/java/com/example/sendowl/auth/exception/enums/JwtErrorCode.java
  src/main/java/com/example/sendowl/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/sendowl/auth/jwt/JwtExceptionFilter.java
  src/main/java/com/example/sendowl/auth/jwt/JwtProvider.java
  src/main/java/com/example/sendowl/common/dto/BaseErrorResponseDto.java
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/resources/application.yml
Labels: enhancement, fix, refactoring

#44 Fix/redis for code reviews
  .gitignore
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/config/RedisConfigure.java
  src/main/java/com/example/sendowl/domain/board/dto/BoardDto.java
  src/main/java/com/example/sendowl/redis/enums/RedisEnum.java
  src/main/java/com/example/sendowl/redis/sub/RedisMessageSubscriber.java
  src/main/java/com/example/sendowl/redis/template/RedisBoard.java
  src/main/java/com/example/sendowl/redis/template/RedisShadow.java
  src/test/java/com/example/sendowl/redis/template/RedisBoardTest.java
Labels: fix, refactoring

#46 Fix/category
  docker-compose.yml
  src/main/java/com/example/sendowl/SendOwlApplication.java
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/domain/board/dto/BoardDto.java
  src/main/java/com/example/sendowl/domain/category/entity/Category.java
  src/main/java/com/example/sendowl/domain/category/entity/CategoryName.java
  src/main/java/com/example/sendowl/domain/category/enums/CategoryErrorCode.java
  src/main/java/com/example/sendowl/domain/category/exception/CategoryNameNotFoundException.java
  src/main/java/com/example/sendowl/domain/category/repository/CategoryRepository.java
  src/test/java/com/example/sendowl/repository/CategoryRepositoryTest.java
Labels: bug, enhancement, fix

#47 Feat/category
  src/main/java/com/example/sendowl/api/controller/CategoryController.java
  src/main/java/com/example/sendowl/api/service/CategoryService.java
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/domain/category/dto/CategoryDto.java
Labels: enhancement

#48 Fix/board
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/domain/board/dto/BoardDto.java
  src/main/java/com/example/sendowl/domain/board/entity/Board.java
Labels: bug, enhancement, fix

#49 Refactor: RedisEmailToken
  .gitignore
  build.gradle
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/api/service/UserService.java
  src/main/java/com/example/sendowl/config/RedisConfigure.java
  src/main/java/com/example/sendowl/kafka/consumer/KafkaConsumer.java
  src/main/java/com/example/sendowl/redis/entity/RedisBoard.java
  src/main/java/com/example/sendowl/redis/entity/RedisEmailToken.java
  src/main/java/com/example/sendowl/redis/repository/RedisBoardRepository.java
  src/main/java/com/example/sendowl/redis/repository/RedisEmailTokenRepository.java
  src/main/java/com/example/sendowl/redis/service/RedisBoardService.java
  src/main/java/com/example/sendowl/redis/service/RedisEmailTokenService.java
  src/main/java/com/example/sendowl/redis/service/RedisShadowKeyService.java
  src/main/java/com/example/sendowl/redis/service/RedisShadowService.java
  src/main/java/com/example/sendowl/redis/sub/RedisMessageSubscriber.java
  src/main/java/com/example/sendowl/redis/template/RedisShadow.java
  src/test/java/com/example/sendowl/redis/service/RedisEmailTokenServiceTest.java
  src/test/java/com/example/sendowl/redis/template/RedisBoardServiceTest.java
Labels: refactoring, new-feature

#51 Feat/board page
  src/main/java/com/example/sendowl/api/controller/BoardController.java
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/domain/board/dto/BoardDto.java
  src/main/java/com/example/sendowl/domain/board/repository/BoardRepository.java
Labels: enhancement, fix
