Repository sendOwlOrganization/SendOwl, pull requests merged in 2022-08, with the labels that each got.

#80 Add file upload API
  src/main/java/com/example/sendowl/api/controller/FileController.java
  src/main/java/com/example/sendowl/api/service/FileService.java
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/domain/file/dto/FileDto.java
Labels: new-feature

#81 Feat/mbti
  src/main/java/com/example/sendowl/api/controller/MbtiController.java
  src/main/java/com/example/sendowl/api/service/UserService.java
  src/main/java/com/example/sendowl/domain/board/repository/BoardRepository.java
  src/main/java/com/example/sendowl/domain/category/entity/Category.java
  src/main/java/com/example/sendowl/domain/user/repository/UserRepository.java
  src/test/java/com/example/sendowl/repository/UserRepositoryTest.java
Labels: enhancement, fix

#82 Multiple files upload
  src/main/java/com/example/sendowl/api/controller/FileController.java
  src/main/java/com/example/sendowl/api/file/FileApi.java
  src/main/java/com/example/sendowl/api/service/FileService.java
Labels: fix, new-feature

#83 Feat/blame
  src/main/java/com/example/sendowl/api/controller/BlameController.java
  src/main/java/com/example/sendowl/api/service/BlameService.java
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/domain/blame/Blame.java
  src/main/java/com/example/sendowl/domain/blame/BlameType.java
  src/main/java/com/example/sendowl/domain/blame/dto/BlameDto.java
  src/main/java/com/example/sendowl/domain/blame/exception/BlameTypeExistException.java
  src/main/java/com/example/sendowl/domain/blame/exception/BlameTypeNotFoundException.java
  src/main/java/com/example/sendowl/domain/blame/exception/enums/BlameErrorCode.java
  src/main/java/com/example/sendowl/domain/blame/exception/handler/BlameTypeExceptionHandler.java
  src/main/java/com/example/sendowl/domain/blame/repository/BlameRepository.java
  src/main/java/com/example/sendowl/domain/blame/repository/BlameTypeRepository.java
Labels: enhancement

#85 Feat/oauth2
  build.gradle
  src/main/java/com/example/sendowl/api/controller/UserController.java
  src/main/java/com/example/sendowl/api/service/UserService.java
  src/main/java/com/example/sendowl/auth/PrincipalDetails.java
  src/main/java/com/example/sendowl/auth/PrincipalDetailsService.java
  src/main/java/com/example/sendowl/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/sendowl/auth/jwt/JwtProvider.java
  src/main/java/com/example/sendowl/config/SecurityConfigure.java
  src/main/java/com/example/sendowl/domain/user/dto/UserDto.java
  src/main/java/com/example/sendowl/domain/user/entity/Role.java
  src/main/java/com/example/sendowl/domain/user/entity/User.java
  src/main/java/com/example/sendowl/domain/user/exception/UserException.java
  src/main/java/com/example/sendowl/domain/user/exception/enums/UserErrorCode.java
  src/main/java/com/example/sendowl/domain/user/repository/UserRepository.java
  src/test/java/com/example/sendowl/oauth/OauthServiceTest.java
Labels: enhancement, fix
