Repository sendOwlOrganization/SendOwl, pull requests merged in 2022-05, with the labels that each got.

#53 Comment delete
  src/main/java/com/example/sendowl/api/controller/CommentController.java
  src/main/java/com/example/sendowl/api/service/CommentService.java
  src/main/java/com/example/sendowl/domain/comment/dto/CommentDto.java
  src/main/java/com/example/sendowl/domain/comment/dto/CommentRequest.java
  src/main/java/com/example/sendowl/domain/comment/entity/Comment.java
  src/main/java/com/example/sendowl/domain/comment/exception/enums/CommentErrorCode.java
  src/main/java/com/example/sendowl/domain/comment/repository/CommentRepository.java
Labels: new-feature

#55 Feat/search
  src/main/java/com/example/sendowl/api/controller/SearchController.java
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/domain/board/repository/BoardRepository.java
  src/main/java/com/example/sendowl/domain/board/specification/BoardSpecification.java
Labels: enhancement

#57 Feat/category
  src/main/java/com/example/sendowl/SendOwlApplication.java
  src/main/java/com/example/sendowl/api/controller/CategoryController.java
  src/main/java/com/example/sendowl/api/service/CategoryService.java
  src/main/java/com/example/sendowl/domain/category/dto/CategoryDto.java
  src/main/java/com/example/sendowl/domain/category/entity/Category.java
  src/main/java/com/example/sendowl/domain/category/entity/CategoryName.java
  src/main/java/com/example/sendowl/domain/category/enums/CategoryErrorCode.java
  src/main/java/com/example/sendowl/domain/category/exception/CategoryNameAlreadyExistsException.java
  src/main/java/com/example/sendowl/domain/category/repository/CategoryRepository.java
  src/test/java/com/example/sendowl/repository/CategoryRepositoryTest.java
Labels: fix, new-feature

#58 Fix/category
  src/main/java/com/example/sendowl/SendOwlApplication.java
  src/main/java/com/example/sendowl/api/service/CategoryService.java
  src/main/java/com/example/sendowl/domain/category/dto/CategoryDto.java
  src/main/java/com/example/sendowl/domain/category/entity/Category.java
  src/main/java/com/example/sendowl/domain/category/repository/CategoryRepository.java
  src/test/java/com/example/sendowl/repository/CategoryRepositoryTest.java
Labels: fix

#59 Fix/board
  src/main/java/com/example/sendowl/api/service/CategoryService.java
  src/main/java/com/example/sendowl/domain/board/dto/BoardDto.java
  src/main/java/com/example/sendowl/domain/category/entity/Category.java
  src/main/java/com/example/sendowl/domain/category/repository/CategoryRepository.java
  src/main/java/com/example/sendowl/domain/user/dto/UserDto.java
Labels: fix

#60 fix: Change active to isDelete
  src/main/java/com/example/sendowl/api/controller/CommentController.java
  src/main/java/com/example/sendowl/api/service/CommentService.java
  src/main/java/com/example/sendowl/common/converter/BooleanToTFConverter.java
  src/main/java/com/example/sendowl/common/entity/BaseEntity.java
  src/main/java/com/example/sendowl/domain/board/repository/BoardRepository.java
  src/main/java/com/example/sendowl/domain/board/specification/BoardSpecification.java
  src/main/java/com/example/sendowl/domain/comment/repository/CommentRepository.java
Labels: fix

#61 Fix comment
  src/main/java/com/example/sendowl/api/controller/CommentController.java
  src/main/java/com/example/sendowl/api/service/CommentService.java
  src/main/java/com/example/sendowl/common/entity/BaseEntity.java
  src/main/java/com/example/sendowl/domain/comment/dto/CommentDto.java
  src/test/java/com/example/sendowl/repository/CommentRepositoryTest.java
Labels: fix

#62 Board delete
  src/main/java/com/example/sendowl/api/controller/BoardController.java
  src/main/java/com/example/sendowl/api/controller/CategoryController.java
  src/main/java/com/example/sendowl/api/controller/CommentController.java
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/api/service/CategoryService.java
  src/main/java/com/example/sendowl/api/service/CommentService.java
  src/main/java/com/example/sendowl/common/entity/BaseEntity.java
  src/main/java/com/example/sendowl/domain/board/dto/BoardDto.java
  src/main/java/com/example/sendowl/domain/board/entity/Board.java
  src/main/java/com/example/sendowl/domain/board/repository/BoardRepository.java
  src/main/java/com/example/sendowl/domain/comment/repository/CommentRepository.java
Labels: new-feature

#64 Feat/docker
  Dockerfile
  build.sh
  docker-compose.yml
  src/main/resources/META-INF/MANIFEST.MF
Labels: enhancement

#66 Fix/board
  src/main/java/com/example/sendowl/api/controller/BoardController.java
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/domain/board/repository/BoardRepository.java
  src/test/java/com/example/sendowl/repository/BoardRepositoryTest.java
Labels: enhancement, fix

#69 Feat/redis
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/redis/service/RedisBoardService.java
  src/test/java/com/example/sendowl/api/service/BoardServiceTest.java
  src/test/java/com/example/sendowl/redis/RedisRepositoryTest.java
  src/test/java/com/example/sendowl/redis/template/RedisBoardServiceTest.java
Labels: enhancement, fix

#67 fix: fix board list dto
  build.gradle
  src/main/java/com/example/sendowl/api/service/BoardService.java
  src/main/java/com/example/sendowl/common/converter/MarkdownToText.java
  src/main/java/com/example/sendowl/domain/board/dto/BoardDto.java
  src/main/java/com/example/sendowl/domain/board/entity/Board.java
Labels: fix
